//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingID { get; set; }
        public int GuestID { get; set; }
        public int InvoiceID { get; set; }
        public int RoomID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public bool IsCancelled { get; set; }
        public byte TotalBeds { get; set; }
    
        public virtual Guest Guest { get; set; }
        public virtual Invoice Invoice { get; set; }
        public virtual Room Room { get; set; }
    }
}
